vesion: 0.2
env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "arn:aws:s3:::nirajcodedeploy"
    BUILD_FOLDER: "commitdemo"
    BUILD_ENV: "prod"
phases:
  install:
    commands: 
      - echo Installing source...
      - npm install
      - npm install -g @angular/cli 
  build:
    commands:
      - echo Build started.
      - ng build --${BUILD_ENV}
  post_build:
    commands:
      - aws s3 cp ${BUILD_FOLDER} s3://${S3_BUCKET} --recursive --acl public-read --cache-control "max-age=${CACHE_CONTROL}" 
      - echo Build completed on `date` 
artifacts:
  files:
    - '**/*' 
  base-directory: 'dist*' 
  discard-paths: yes 
      